version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: monthly

updates:
  - package-ecosystem: uv
    directory: /
    multi-ecosystem-group: python
    groups:
      python-runtime:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
